### PR TITLE
Update codebase to use es5 trailingComma

### PR DESCRIPTION
**Pull request by ismail-syed**
* Format project codebase to use `es5` style for trailing comma so we don't break projects that are on node version 6 😥

### CODE REVIEW

**Review by lemonmade — APPROVED** [review]

**Comment by kaelig** [comment]
The `comma-dangle` rule is still throwing errors in projects that don't use Prettier (seen in `polaris-react` when upgrading from v17 to v19-beta). Can we also fix this issue?

**Comment by lemonmade** [comment]
What errors are you seeing? This fix was about this package itself not using trailing commas because it has to run in node, Polaris has a build step where they are stripped out so it is supposed to throw errors if there are no trailing commas in the source.

**Comment by ismail-syed** [comment]
Do you have a branch I can look at?

**Comment by kaelig** [comment]
Yes, you can have a look over there: https://github.com/Shopify/polaris-react/pull/885

**Comment by lemonmade** [comment]
@kaelig you'll have to add a separate .eslintrc.js/ use glob patterns in your eslintrc to specify different rules for non-source files if they can't be run as-is when following the rule, it's not something we are really optimizing for given that we mostly just have to lint files that get compiled in some way.

**Comment by kaelig** [comment]
Thanks, that's starting to make sense.

It's quite a bit of added cognitive load, could we align on one single setting for a more consistent DX?

Here are a few solutions I can think of:
- keep `'comma-dangle': 'all'`, and stop supporting Node 6 (version 8 is LTS after all)
- keep `'comma-dangle': 'all'`, and add a prepublish script to transpile the npm package down to es5
- revert the rule to follow `'comma-dangle': 'es5'` everywhere

**Comment by ismail-syed** [comment]
> keep 'comma-dangle': 'all', and stop supporting Node 6 (version 8 is LTS after all)

I prefer this, that way we force the org to update to node 8.

**Comment by lemonmade** [comment]
I am still not sure I understand. This is a project-level configuration issue, nothing to do with our linting config. We specify different configs for different environments, it's up to the user to choose the right one for them. Moving to Node 8 simplifies this because no project has to choose between comma dangle or not, but there will be other issues for which the answer is the same.

**Pull request merged**
