### PR TITLE
v19.0.0 🎩

### PR DESCRIPTION
**Pull request by kaelig**
Let's tophat v19.0.0 with this beta!

```
yarn add -D eslint-plugin-shopify@19.0.0-beta.4
```

- [x] polaris-react @kaelig [Open PR](https://github.com/Shopify/polaris-react/pull/885)
- [x] shopify/web @goodforonefare [Merged PR](https://github.com/Shopify/web/pull/2473)
- [x] sewing-kit @goodforonefare [Merged PR](https://github.com/Shopify/sewing-kit/pull/491)

### CODE REVIEW

**Comment by kaelig** [comment]
I'm getting these `comma-dangle` errors in `polaris-react`, but fixing them breaks compat with Node v6:

```
error: Missing trailing comma (comma-dangle) at config/jest/transformers/typescript.js:21:11:
  19 |         tsConfig.compilerOptions,
  20 |         path,
> 21 |         []
     |           ^
  22 |       );
  23 |
  24 |       const fakeJSPath = path.replace(/\.tsx?$/, '.js');


error: Missing trailing comma (comma-dangle) at scripts/public-repo-deploy.js:111:86:
  109 | writeFileSync(
  110 |   publicReadme,
> 111 |   readFileSync(publicReadme, 'utf8').replace(/\{\{VERSION\}\}/g, packageJSON.version)
      |                                                                                      ^
  112 | );
  113 |
  114 | // Replace variables in the component README with the appropriate details


error: Missing trailing comma (comma-dangle) at scripts/public-repo-deploy.js:118:89:
  116 | writeFileSync(
  117 |   componentReadme,
> 118 |   readFileSync(componentReadme, 'utf8').replace(/\{\{VERSION\}\}/g, packageJSON.version)
      |                                                                                         ^
  119 | );
  120 |
  121 | // Used to make git operations in polarisPublic dir instead of current working dir
```

This is related to #61

**Comment by kaelig** [comment]
19.0.0-beta.4 works well on polaris-react, see this PR: https://github.com/Shopify/polaris-react/pull/885

@ismail-syed, can you test on shopify/web and sewing-kit?

**Comment by GoodForOneFare** [comment]
Ismail is part time right now.  I'll test out other repos.

**Comment by kaelig** [comment]
@GoodForOneFare any updates on shopify/web?

**Comment by kaelig** [comment]
Oops, I hadn’t seen the open PR. Don’t mind my previous message.

**Comment by GoodForOneFare** [comment]
`sewing-kit` and `web` are now using the v19 beta.  `fix-class-property-no-initializer` needs a bugfix, but I'm about to [review the PR for that](https://github.com/Shopify/eslint-plugin-shopify/pull/76).

I reckon we should wait for that bugfix, then :shipit:

**Pull request merged**
